# Generated by Django 5.0.6 on 2024-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_delete_getintouch_delete_mainportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='job',
            field=models.CharField(default='1', max_length=77),
            preserve_default=False,
        ),
    ]
