# Generated by Django 5.0.6 on 2024-07-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_personalinfo_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default='1', max_length=111),
            preserve_default=False,
        ),
    ]
