# Generated by Django 5.0.6 on 2024-07-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_personalinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(default=0, max_length=3),
        ),
    ]
