# Generated by Django 5.0.6 on 2024-07-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_portfolioinfo_image_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinfo',
            name='client_url',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='category',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='client',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='example_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='name',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioinfo',
            name='project_url',
            field=models.URLField(blank=True, max_length=222, null=True),
        ),
    ]
