# Generated by Django 5.0.6 on 2024-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_portfolioinfo_client_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioinfo',
            name='project_date',
            field=models.CharField(blank=True, max_length=77, null=True),
        ),
    ]
