# Generated by Django 5.0.6 on 2024-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_portfolioinfo_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioinfo',
            name='project_date',
            field=models.CharField(blank=True, max_length=77, null=True, verbose_name='loyiha vaqti misol uchun: 2024-07-08\nyoki 2024-07-08 20:48:50'),
        ),
    ]
